# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6eb401107e062ba43d2794c276240c91205afde52188cefa6227e1e9a3bad15cc93f985f8867641bdb349686101ed4884aa4bbe572d0c213a51ea7b04f677d83

test:
  secret_key_base: 88f3746457e479cff671fb98b13665f5f91c486f6af2bb0946b1bbc83f507ed9ad7426238b339b106d4caaa086630a6d8dcc0e61d247fe69a4f4def5a51ac3e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
